codecov:
  notify:
    require_ci_to_pass: yes
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project: yes
    patch: yes
    changes: no

beta_groups:
  - "labels"

flag_management:
  default_rules:
    carryforward: false
    statuses:
      - name_prefix: "app."
        type: "project"
        carryforward_behavior: "exclude"
        flag_coverage_not_uploaded_behavior: "exclude"
  individual_flags:
    - name: unit-with-labels
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "patch"
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: actual_code
      name: NonTestCode
      paths:
        - "!conftest.py"
        - "!**/conftest.py"
        - "!**tests**/test_*.py"
    - component_id: ascii
      paths:
        - "**/ascii.py"
    - component_id: emoji
      paths:
        - "**/emoji.py"

comment:
  layout: "header, reach, diff, flags, components, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes