codecov:
  project:
    enabled: false
  patch:
    only_pulls: true
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project: yes
    patch: yes
    changes: no

flag_management:
  default_rules:
    carryforward: false
    statuses:
      - name_prefix: "app."
        type: "project"
        carryforward_behavior: "exclude"
        flag_coverage_not_uploaded_behavior: "exclude"
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "patch"
          enabled: false

component_management:
  default_rules:
    statuses:
      - type: patch
        target: auto
  individual_components:
    - component_id: actual_code
      name: NonTestCode
      paths:
        - "!conftest.py"
        - "!**/conftest.py"
        - "!**tests**/test_*.py"
    - component_id: ascii
      paths:
        - "**/ascii.py"
    - component_id: emoji
      paths:
        - "**/emoji.py"


cli:
  plugins:
    pycoverage:
      report_type: "json"
    compress-pycoverage:
      file_to_compress: ".artifacts/core.coverage.json"
      # We don't want to upload the original coverage report by accident
      # Because it's too big
      delete_uncompressed: true
  runners:
    python:
      collect_tests_options:
        - "core"