name: All Teams Workflow

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: core
          - app: fruits
          - app: emotions
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage (with labels)
      run: |
        python -m pytest ${{ matrix.app }}/** --cov=./${{ matrix.app }}  --cov-report="xml:.artifacts/${{ matrix.app }}.coverage.xml" --cov-context=test
        coverage json -o .artifacts/${{ matrix.app }}.coverage.json --show-contexts
    - name: Upload to codecov
      uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378  # v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.app }}
        files: .artifacts/${{ matrix.app }}.coverage.xml
        verbose: true
      continue-on-error: true
    # This is temporary because codecov/codecov-action@v4-beta
    # Doesn't support --disable-search option
    # And we don't want to upload random reports (for safety)
    - name: Clean XML report
      if: ${{ matrix.app  == 'core' }}
      run: |
        rm .artifacts/core.coverage.xml
    - name: Upload to codecov - special case test ATS
      if: ${{ matrix.app  == 'core' }}
      uses: codecov/codecov-action@v4-beta
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: .artifacts/core.coverage.codecov.json
        flags: smart-tests
        plugins: compress-pycoverage
      continue-on-error: true