name: All Teams Workflow

on:
  push:

jobs:
  codecov-startup:
    runs-on: ubuntu-latest
    name: Startup Codecov Info
    steps:
    - name: Install Codecov CLI from pip
      run: |
        pip install pytest codecov-cli
    - name: Save commit info 
      run: |
        codecovcli create-commit --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
    - name: Create report
      run: |
        codecovcli create-report --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
  build-and-test:
    needs: codecov-startup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: core
            delay: 0
          - app: fruits
            delay: 300
          - app: emotions
            delay: 303
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage (with labels)
      run: python -m pytest ${{ matrix.app }}/** --cov=./${{ matrix.app }} --cov-context=test
    - name: Fix coverage format
      run: |
        coverage json --show-contexts -o label.coverage.json
        rm .coverage
    - name: Introduce some delay in the receiving of reports
      run: sleep ${{ matrix.delay }}
    - name: Install Codecov CLI from pip
      run: |
        pip install pytest codecov-cli
    - name: Upload coverage to codecov using CLI
      run: |
        codecovcli --verbose do-upload --flag unit-with-labels --token=${{ secrets.CODECOV_TOKEN }} --fail-on-error