name: smart test selection

on: [push]

jobs:
  # install-codecov-cli:
  #   uses: ./.github/workflows/download_cli.yml
  static-analysis:
    # needs: install-codecov-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Install Codecov CLI from pip
        run: |
          pip install pytest codecov-cli
      - name: Save commit info 
        run: |
          codecovcli create-commit --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
      - name: Create report
        run: |
          codecovcli create-report --git-service=github --token=${{ secrets.CODECOV_TOKEN }}
      - name: Run Static Analysis
        run: |
          codecovcli static-analysis --token=${{ secrets.STATIC_TOKEN }}
  iterative-testing:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Install Pytest and its dependencies
        run: |
          pip install pytest pytest-cov pytest-mock
      - name: Install Codecov CLI from pip
        run: |
          pip install codecov-cli
      - name: Run smart test selection
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.sha }}^ origin/main)
          echo "Using base commit ${BASE_COMMIT}"
          codecovcli label-analysis --token=${{ secrets.STATIC_TOKEN }} --base-sha=${BASE_COMMIT}
          coverage json --show-contexts -o label.coverage.json
          rm .coverage
          codecovcli --verbose do-upload --flag smart-tests --file=label.coverage.json --token=${{ secrets.CODECOV_TOKEN }}  --fail-on-error
